WebAppWithRazorPages/ToDoApp/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoApp.Pages;

[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
[IgnoreAntiforgeryToken]
public class ErrorModel : PageModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

    private readonly ILogger<ErrorModel> _logger;

    public ErrorModel(ILogger<ErrorModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
        RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
    }
}

WebAppWithRazorPages/ToDoApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ToDoApp.Model;
using ToDoApp.Services;

namespace ToDoApp.Pages;

public class IndexModel : PageModel
{
    private readonly IToDoDataService service; 

    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger, IToDoDataService service)
    {
        _logger = logger;
        this.service = service;
    }

    // use Url.Page() method to generate links 

    public IActionResult OnGet()
    {
        TodoList = service.GetAllToDoTasks();
        return Page();
    }

    public IActionResult OnPostToDoCompleted(int toDoID)
    {
        service.UpdateToDoToCompletedByID(toDoID);
        return RedirectToPage("Index");
    }

    // Data shared with razor view 
    public List<TodoModel> TodoList { get; private set; } = new List<TodoModel>();
}

WebAppWithRazorPages/ToDoApp/Pages/MissingPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoApp.Pages
{
    public class MissingPageModel : PageModel
    {
        public string? errorCode { get; private set; }

        public IActionResult OnGet(string? error)
        {
            errorCode = error; 
            return Page();
        }
    }
}

WebAppWithRazorPages/ToDoApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ToDoApp.Pages;

public class PrivacyModel : PageModel
{
    private readonly ILogger<PrivacyModel> _logger;

    public PrivacyModel(ILogger<PrivacyModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {
    }
}

WebAppWithRazorPages/ToDoApp/Pages/Index.cshtml
@page "{handler?}"
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<article>
    <section class="TodoSection">
        <div>
            <a href="#">Create New</a>
        </div>
        <table class="table table-bordered text-center">
            <thead>
                <tr>
                    <th></th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Date Created</th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                @if(Model.TodoList.Any(t => !t.isCompleted))
                {
                    <tr>
                        <td rowspan="@(Model.TodoList.Count() +1)">UnCompleted</td>
                    </tr>
                    @foreach (var todoModel in Model.TodoList)
                    {
                        <tr>
                            @if (!todoModel.isCompleted)
                            {
                                <td>@todoModel.Name</td>
                                <td>@todoModel.Description</td>
                                <td>@todoModel.CreatedDate.ToString("D")</td>
                                <td>
                                    <form asp-page-handler="ToDoCompleted" method="post">
                                        <input type="hidden" name="toDoID" value="@todoModel.Id" />
                                        <button type="submit">Completed</button>
                                    </form>
                                </td>
                                <td><a href="#">Edit</a></td>
                                <td><a href="#">Delete</a></td>
                            }
                        </tr>
                    }
                }
                
                @if(Model.TodoList.Any(t => t.isCompleted))
                {
                    <tr>
                        <td rowspan="@(Model.TodoList.Count() +1)">Completed</td>
                    </tr>
                    @foreach (var todoModel in Model.TodoList)
                    {
                        <tr>
                            @if (todoModel.isCompleted)
                            {
                                <td>@todoModel.Name</td>
                                <td>@todoModel.Description</td>
                                <td>@todoModel.CreatedDate</td>
                                <td></td>
                                <td><a href="#">Edit</a></td>
                                <td><a href="#">Delete</a></td>
                            }
                        </tr>
                    }
                }
            </tbody>

        </table>

    </section>
</article>

WebAppWithRazorPages/ToDoApp/Pages/MissingPage.cshtml
@page "{error?}"
@model ToDoApp.Pages.MissingPageModel
@{
    ViewData["Title"] = "Page Missing";
}


<h2>Page missing</h2>
<p>Page does not Exists</p>
<p>Error: @Model.errorCode</p>

WebAppWithRazorPages/ToDoApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ToDoApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ToDoApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ToDoApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - ToDoApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>